import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef } from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HelpCircle } from "lucide-react";

const faqs = [
  {
    question: "What is Dr. Zoe?",
    answer:
      "Dr. Zoe is an AI-powered healthcare assistant that provides comprehensive health diagnostics, automated vital sign measurements, and tele-medical support. It combines advanced artificial intelligence with integrated health sensors to deliver accurate preliminary health assessments and connect patients with certified healthcare professionals.",
  },
  {
    question: "How does AI diagnosis work?",
    answer:
      "Our AI diagnosis system analyzes data collected from integrated sensors (blood pressure, heart rate, SpO2, temperature) along with your symptoms and medical history. The AI uses advanced machine learning algorithms trained on millions of medical cases to identify patterns and provide preliminary health assessments. These results are always reviewed by qualified medical professionals for accuracy.",
  },
  {
    question: "Is this technology safe?",
    answer:
      "Absolutely. Dr. Zoe adheres to strict medical safety standards and is HIPAA compliant, FDA approved, and ISO certified. All data is encrypted and stored securely. The AI provides preliminary assessments only, and all diagnoses are verified by licensed healthcare professionals. We never replace professional medical advice but complement it with accessible preliminary screening.",
  },
  {
    question: "Can I share my health reports?",
    answer:
      "Yes, all health reports generated by Dr. Zoe can be easily shared. You can download PDF versions, email them directly to your personal doctor, or share them with family members through our secure sharing feature. Reports are also stored in your personal health dashboard for future reference and tracking health trends over time.",
  },
  {
    question: "Where can I access the Dr. Zoe app?",
    answer:
      "Dr. Zoe is available through multiple channels. You can access it via our dedicated kiosks placed in clinics, pharmacies, and healthcare facilities. We also offer a mobile app for iOS and Android for home health monitoring. For full diagnostic capabilities including sensor measurements, visit one of our kiosk locations.",
  },
];

export function FAQ() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  return (
    <section id="faq" className="section-padding bg-muted/30" ref={ref}>
      <div className="container mx-auto">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Find answers to common questions about Dr. Zoe and how our AI-powered
            healthcare solution can help you.
          </p>
        </motion.div>

        {/* FAQ Accordion */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="max-w-3xl mx-auto"
        >
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="bg-card border border-border rounded-xl px-6 data-[state=open]:border-primary/30 transition-colors"
              >
                <AccordionTrigger className="text-left hover:no-underline py-5">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center flex-shrink-0">
                      <HelpCircle className="w-4 h-4 text-primary-foreground" />
                    </div>
                    <span className="font-semibold text-foreground">
                      {faq.question}
                    </span>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground pb-5 pl-11">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>

        {/* Still Have Questions CTA */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="text-center mt-12"
        >
          <p className="text-muted-foreground mb-4">
            Still have questions? We're here to help!
          </p>
          <a
            href="#contact"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-full gradient-bg text-primary-foreground font-medium hover:opacity-90 transition-opacity"
          >
            Contact Us
          </a>
        </motion.div>
      </div>
    </section>
  );
}
